### ISSUE TITLE
Provide kuberay-tpu-webhook image in Europe to save on network egress?

### ISSUE THREAD

**Issue by davidxia** [GoogleCloudPlatform/ai-on-gke#311]
My GKE cluster is in europe-west4-b. It'd be great to have an equivalent `us-docker.pkg.dev/ai-on-gke/kuberay-tpu-webhook/kuberay-tpu-webhook` image in Europe to reduce network egress costs. 🙏

**Comment by ryanaoleary** [comment]
Automatic builds for the Ray webhook are now getting pushed for Europe here: `europe-docker.pkg.dev/ai-on-gke/kuberay-tpu-webhook/tpu-webhook`. I've tagged the release with the latest changes `v1.1`.
