### ISSUE TITLE
Only set CLOUDSQL_INSTANCE_CONNECTION_NAME env var in Ray clusters when deploying RAG

### ISSUE THREAD

**Issue by andrewsykim** [GoogleCloudPlatform/ai-on-gke#424]
The kuberay-cluster module always sets the CLOUDSQL_INSTANCE_CONNECTION_NAME environment variable, even when deploying `applications/ray` without the RAG part. 

CLOUDSQL_INSTANCE_CONNECTION_NAME should be optional and only set when needed for RAG

**Comment by german-grandas** [comment]
Issue tracked and fixed on https://github.com/GoogleCloudPlatform/ai-on-gke/issues/435
