### ISSUE TITLE
JupyterHub default profile options should only be "CPU" and "L4 GPU" 

### ISSUE THREAD

**Issue by andrewsykim** [GoogleCloudPlatform/ai-on-gke#433]
Our guides mostly use L4 GPUs now, the default profiles in the JupyterHub configuration should reflect this. Currently they allow use of T4s, A100 and TPUs.

**Comment by german-grandas** [comment]
Currently when you are in the screen to select a profile configuration for a jupyter server, it only allow to select L4 GPU.
![jupyter_img](https://github.com/user-attachments/assets/d54f6c9e-ba33-47ca-8abd-e94a6980a50a)
