### ISSUE TITLE
Update the README to reflect the correct sample dataset & surface this info earlier in the README

### ISSUE THREAD

**Issue by kumar-dhanagopal** [GoogleCloudPlatform/ai-on-gke#438]
1. Currently, https://github.com/GoogleCloudPlatform/ai-on-gke/blob/main/applications/rag/README.md mentions that the example uses https://www.kaggle.com/datasets/denizbilginn/google-maps-restaurant-reviews as the input dataset. However, per https://github.com/GoogleCloudPlatform/ai-on-gke/pull/385, the example uses a "Netflix shows" dataset.

2. To help users quickly understand what the sample application does, consider mentioning the example dataset upfront in the introductory section of the README. Currently, the dataset info is buried rather deep in the README.

**Comment by andrewsykim** [comment]
Adding to this, the value of `TABLE_NAME` is still googlemaps_reviews_db, should be `netflix_reviews_db` or

**Comment by andrewsykim** [comment]
I believe @imreddy13 is working on this already https://github.com/GoogleCloudPlatform/ai-on-gke/pull/445
