### ISSUE TITLE
Switch all quick start deployments to use Autopilot by default

### ISSUE THREAD

**Issue by andrewsykim** [GoogleCloudPlatform/ai-on-gke#573]
We switched our quick start deployments to use GKE Standard due to flakes when attempting to run the GMP module (https://github.com/GoogleCloudPlatform/ai-on-gke/pull/418) and other issues during testing. Once the remaining issues are resolved we should switch everything back to using Autopilot

**Comment by andrewsykim** [comment]
cc @artemvmin

**Comment by artemvmin** [comment]
cc @roberthbailey is driving this
