### ISSUE TITLE
Error 400: Autopilot clusters must be regional clusters

### ISSUE THREAD

**Issue by kzos** [GoogleCloudPlatform/ai-on-gke#628]
1.
I am trying to instantiate the ray cluster on GKE following this tutorial:
https://github.com/GoogleCloudPlatform/ai-on-gke/blob/main/ray-on-gke/README.md

with below settings in workloads.tfvars:-

project_id = "deployment_work"

cluster_name = "vm-deploy-k8-fsz"

cluster_location = "me-central1-a"

create_cluster = true
================================>

2. But getting this below error:

╷
│ Error: googleapi: Error 400: Autopilot clusters must be regional clusters.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.RequestInfo",
│     "requestId": "0x4861d29cd332588e"
│   }
│ ]
│ , badRequest
│ 
│   with module.infra[0].module.public-gke-autopilot-cluster[0].module.gke.google_container_cluster.primary,
│   on .terraform/modules/infra.public-gke-autopilot-cluster.gke/modules/beta-autopilot-public-cluster/cluster.tf line 22, in resource "google_container_cluster" "primary":
│   22: resource "google_container_cluster" "primary" {
│ 
╵

Could you please guide me to get create_cluster working.

==================================================>
NOTE: Initially i tried to create the kubernetes cluster in the GCP and gave above setting parameters with "create_cluster = false", cluster_name="vm-deploy-k8-fz" to verify my project id and cluster name, terraform apply ran without any error.

but I am not sure how do i attach to the existing cluster on the GCP(there is no guide on this in readme for newbies). 
$ kubectl get raycluster
--> does not return anything :(

provide guide for this as well.
==================================================>

**Comment by roberthbailey** [comment]
Please set `cluster_location` to a GCP region, such as `me-central1` rather than a zone.

**Comment by kzos** [comment]
sure, thanks I guess I did the same and went past through and getting new error, 

ll mark this as closed and create as new issue.
