### ISSUE TITLE
Terraform in benchmarking has impossible provider requirements

### ISSUE THREAD

**Issue by christopher-hendrich-sada** [GoogleCloudPlatform/ai-on-gke#834]
Not sure what I am doing wrong, but when I try to run the TF code for stage-1, I am getting this: 
terraform init
Initializing the backend...
Initializing modules...
Initializing provider plugins...
- Finding hashicorp/google versions matching ">= 5.12.0, < 6.0.0, >= 6.1.0, < 7.0.0"...
- Finding hashicorp/google-beta versions matching ">= 5.12.0, < 6.0.0, >= 6.1.0, < 7.0.0"...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 5.12.0, < 6.0.0, >= 6.1.0, < 7.0.0
╵
╷
│ Error: Failed to query available provider packages
│ 

Looks like the modules have provider version requirements that are impossible to meet. Lower than 6.0.0 and higher or equal to 6.1.0? I am using cloudshell with terraform upgraded to 1.9.6-1. Anyone else having that issue?

**Comment by Bslabe123** [comment]
This does appear to be an issue with the module, if feasible use Terraform 1.8.4 as a hotfix until a fix is implemented, will follow up.

**Comment by christopherhendrich** [comment]
I tried terraform 1.8.4 in a fresh clone of the repo with the same results.

**Comment by rick-c-goog** [comment]
it is the same for terraform 1.9.8

**Comment by annapendleton** [comment]
I checked the underlying module that it failed at, it's missing the fixed version tag.

Fix in https://github.com/GoogleCloudPlatform/ai-on-gke/pull/885
